name: py38
channels:
  - conda-forge
dependencies:
  - python=3.8
  - streamlit
  - pathlib
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - plotly
  - statsmodels
  - scipy
  - scikit-learn
  - pip: 
      - pathlib
      - pandas
      - numpy
      - seaborn
      - matplotlib
      - plotly
      - statsmodels
      - scipy
      - scikit-learn
      - tensorflow
      - keras
      - lazypredict
      - hummingbird-ml
      - pandas-profiling
      - streamlit-pandas-profiling
